### ISSUE TITLE
DAO schemes don't all have names

### ISSUE THREAD

**Issue by tibetsprague** [daostack/subgraph#202]
Querying for dao.schemes the only Scheme that has a name set is ContributionReward. It would be helpful to have a name set for SchemeRegistrar and others so we know which schemes the DAO has and can display accordingly

**Comment by orenyodfat** [comment]
currently schemes names are set upon the first proposal on this scheme. this is because subgraph is waiting for an event to know how to map address to name. 
you can confirm that by proposing on these schemes.

Right, this is not good as we should be able to present schemes names even before any proposal.
Also there might be future schemes without proposing mechanism.

please note that the client can get the schemes names by query the subgraph .which might be preferable option.

e.g [query](https://subgraph.daostack.io/subgraphs/graphql?query=%23%20Welcome%20to%20GraphiQL%0A%23%0A%23%20GraphiQL%20is%20an%20in-browser%20tool%20for%20writing%2C%20validating%2C%20and%0A%23%20testing%20GraphQL%20queries.%0A%23%0A%23%20Type%20queries%20into%20this%20side%20of%20the%20screen%2C%20and%20you%20will%20see%20intelligent%0A%23%20typeaheads%20aware%20of%20the%20current%20GraphQL%20type%20schema%20and%20live%20syntax%20and%0A%23%20validation%20errors%20highlighted%20within%20the%20text.%0A%23%0A%23%20GraphQL%20queries%20typically%20start%20with%20a%20%22%7B%22%20character.%20Lines%20that%20starts%0A%23%20with%20a%20%23%20are%20ignored.%0A%23%0A%23%20An%20example%20GraphQL%20query%20might%20look%20like%3A%0A%23%0A%23%20%20%20%20%20%7B%0A%23%20%20%20%20%20%20%20field(arg%3A%20%22value%22)%20%7B%0A%23%20%20%20%20%20%20%20%20%20subField%0A%23%20%20%20%20%20%20%20%7D%0A%23%20%20%20%20%20%7D%0A%23%0A%23%20Keyboard%20shortcuts%3A%0A%23%0A%23%20%20Prettify%20Query%3A%20%20Shift-Ctrl-P%20(or%20press%20the%20prettify%20button%20above)%0A%23%0A%23%20%20%20%20%20%20%20Run%20Query%3A%20%20Ctrl-Enter%20(or%20press%20the%20play%20button%20above)%0A%23%0A%23%20%20%20Auto%20Complete%3A%20%20Ctrl-Space%20(or%20just%20start%20typing)%0A%23%0A%0A%7B%0A%20%20ethereumContractSources%7B%0A%20abi%0A%20%20%20%20address%0A%7D%20%20%20%20%20%20%20%20%20%20%0A%7D)

**Comment by tibetsprague** [comment]
@orenyodfat seems like since that info is available in the subgraph it would make sense for the subgraph itself to use it to populate the scheme names so we can do it all in one query.

**Comment by orenyodfat** [comment]
yea. though currently I am not familiar of a way to do that within the subgraph it self. (query subgraph during mapping ).

**Comment by jellegerbrandy** [comment]
With the fresh v17 docker images, the SchemeRegistrar is not showing up at all among the queues: 
```{
           gpqueues {
            id

            dao {
              id
            }
            scheme {
              name
            }
          }
          }
```
This is a problem that we cannot resolve by running the subgraphs query either, it seems.

**Comment by jellegerbrandy** [comment]
ok, after talking with orden we decided to resolve this in the client
