### ISSUE TITLE
accountsWithUnclaimedRewards removes addresses also when rewards are still unclaimed

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#206]
If we redeem, for example, only the nativeToken rewards but not the ETH rewards, the address of the beneificiary will be removed from accountsWithUnclaimedRewards. But the ETH rewards are still there to redeem.

This occurs naturally if we use the `Redeem.contributionRewardRedeem` function when the ETH balance of the DAO avatar is not high enough to reward the user.

**Comment by ben-kaufman** [comment]
@jellegerbrandy Are you sure this issue exists? The code seems to make sure everything was redeemed before removing the account.

**Comment by ben-kaufman** [comment]
Ok, I understand the problem. The accountsWithUnclaimedRewards is specifically for GP rewards, while you're looking for Contribution Reward rewards. These are 2 different types of rewards, and we're not handling the CR rewards in the domain layer, only in the mappings layer (see https://github.com/daostack/subgraph/blob/master/src/mappings/ContributionReward/mapping.ts#L30). Do you any changes to this current process, if so, what is the behavior you'd expect to have?

**Comment by jellegerbrandy** [comment]
So to start with what we need. On the rewards page, we are showing all proposals for which the current user can claim rewards. So a proposal willb e in this list if the user has rewards to claim either from the GPprotocol or from the contribution rewards. We then use the `redeem` function of the Redeemer.sol to claim the rewards.

It is not very nice to mix the generic GP logic witht he specific contributionreward logic, but we are not going to change that in this stage, I think. We had a rpevious subgraph version designed buy Matan in which we had a `rewards` entity that contained all the separate rewards, and that was a good approach, but perhaps too big of  a change now.

In any case, we need a query that givesus all proposals with unclaimed rewards from either GP or CR. 
The smallest change, probably, would be to delete acconts from `accountswithreardstoclaim`  only when all GP and CR rewards have been claimed.

(I need to add here that it is not clear to me yet how we are going to handle the execution of genericschemes and other schemes in alchemy,  which is related, and so we may want to change this behavior later)

**Comment by ben-kaufman** [comment]
@jellegerbrandy I started implementing it, but I have an issue with it. Since the contribution reward supports periods for rewarding, a user might have no current rewards to claim but will have after the period time passes, so I can't tell if the user should or shouldn't be in the unclaimed array.
Any suggestion for how to tackle that?

**Comment by jellegerbrandy** [comment]
see my comments on discord :-)

**Comment by tibetsprague** [comment]
One additional feature we need is that the redemptions page is also supposed to show proposals where the contribution reward beneficiary still has unredeemed rewards, even if they are different from the current user. This is because the proposal may have a negative reputation reward and of course the "beneficiary" would never redeem this "reward" so we need someone else to redeem it for them

**Comment by ben-kaufman** [comment]
I'm not sure what do you mean, this sounds like an Alchemy implementation detail, not something related to the subgraph.
