### ISSUE TITLE
v19 (and v20) fail on rinkeby

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#250]
Basically, they stop indexing proposals.

this is the error message:
```
ubuntu@ip-172-31-22-45:~/subgraph-rinkeby$ sudo docker-compose logs graph-node | grep ERR
graph-node_1  |      May 31 14:27:18.646 ERRO slog-async: logger dropped messages due to channel overflow, count: 127
graph-node_1  |    May 31 14:47:31.497 ERRO Subgraph instance failed to run: Failed to process trigger: Failed to handle Ethereum event with handler "handleStateChange": Trap: Trap { kind: Host(HostExportError("Failed to call function \"redeem\" of contract \"GenesisProtocol\": ABI error: please ensure the contract and method you\'re calling exist! failed to decode empty bytes. if you\'re using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don\'t exist")) }, code: SubgraphSyncingFailure, id: QmPEKgbFN2a5NsiYG8FVzV4NksebT21Dud5MdrVBtx89VJ
```
And this is the empty rpoposals list: 

https://rinkeby.subgraph.daostack.io/subgraphs/name/v19/graphql?query=%7B%0A%20proposals%20%7B%0Atitle%0A%7D%0A%7D

**Comment by jellegerbrandy** [comment]
also v17., which is deployed on the same instance, stopped indexing, so it is not clear to me at all where the bug is

http://ec2-3-19-3-204.us-east-2.compute.amazonaws.com:8600/subgraphs/graphql?query=%7B%0A%20%20%20%20subgraphs%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20currentVersion%20%7B%0A%0A%20%20%20%20%20%20%20%20deployment%20%7B%0A%09%09%09%09%09latestEthereumBlockNumber%0A%20%20%20%20%20%20%20%20%20%20totalEthereumBlocksCount%0A%20%20%20%20%20%20%20%20%20%20synced%0A%20%20%20%20%20%20%20%20%20%20entityCount%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%0A%20%20%20%0A%20%20%20%20%0A%20%20%20%20%20%20%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A

**Comment by jellegerbrandy** [comment]
I'd say this points also to a graph-node bug: we have one single error but basically two different broken subgraphs (v19 that is not indexing any proposals, v17 that just stopped indexing)

**Comment by orenyodfat** [comment]
well,  I see that v19 still indexing.
v17 stop indexing and indeed have failure.

**Comment by orenyodfat** [comment]
finding : 
1 . the failure happened on block 4420127 https://rinkeby.etherscan.io/tx/0x7527fde9594ee41739ff269ee35e4f3c42628c19ffe30977cb06160759d1ddec  .
2. the dao is an old one , which does not appease on latest migration. "0xb89370c74d929ca24daeb000e8f90b8c9685d375" .
3. the proposal is scheme registrar proposal , while trying to register upgrade scheme proposal .
    the proposal id is 0x429603d0684dc96bbebd7a042b7216327cc8919f3a0ff1d0c890ee5da8ab5488 
4. the failure happened upon executeboosted on this proposal
5. it is consistence ,as I succeed reproduce the same issue again on my local machine , while indexing Rinkeby.  
6. see http://ec2-3-19-3-204.us-east-2.compute.amazonaws.com:8400/subgraphs/name/v20/graphql?query=%0A%7B%0A%0A%20%20%20%20proposal(id%3A%220x429603d0684dc96bbebd7a042b7216327cc8919f3a0ff1d0c890ee5da8ab5488%22)%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%20%20stage%0A%20%20%20%20%20%20schemeRegistrar%7B%0A%20%20%20%20%20%20%20%20schemeToRegister%0A%20%20%20%20%20%20%20%20schemeRegistered%0A%20%20%20%20%20%20%20%20schemeToRegisterPermission%0A%20%20%20%20%20%20%20%20schemeToRegisterParamsHash%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%7D%0A%20%20%20%20dao%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%7D 
7. still not sure re the root cause of the issue.
8. the empty proposals list which is mention in this issue is due to the fact that subgraph does not index rc 1Ams 6 on Rinkeby . will fix that.

**Comment by jellegerbrandy** [comment]
to be clear: yes, v19 is still indexing, but it is has not indexed any proposals. And we have another instance (not running, I turend it off, the server is very busy) with just v20 with the same error and the same empty proposals list.  (Perhaps the stopping of v17 and the lack of proposals in v19 are independent bugs, but they appeared at the same time...)

**Comment by orenyodfat** [comment]
Please see the pr to fix the no proposal issue

**Comment by orenyodfat** [comment]
my suspection is that it related to many mapping events on the same block 4420127 .
seems like the(a) bot called executeboosted on multiple proposal on the sane time...and the graph is overloaded.
will investigate that further.

**Comment by ben-kaufman** [comment]
I'm working on it for now. Trying first to see if I can replicate that faster in a small test.

**Comment by jellegerbrandy** [comment]
The root fo the problem must be something in the code, though (also perhaps subgraph version), because the v17 that is running on port 8300 does not have any problems at all, it seems:

https://rinkeby.subgraph.daostack.io/subgraphs/graphql?query=%7B%20subgraphs%20%7B%20id%20name%20%0AcurrentVersion%20%7B%0A%20%20deployment%20%7B%0A%20%20%20%20%0A%20%20%20%20totalEthereumBlocksCount%0A%20%20%20%20latestEthereumBlockNumber%0A%20%20%7D%0A%7D%0A%7D%7D%0A%20%20%0A is indexing without problems.

**Comment by orenyodfat** [comment]
it might be due to the fact that this proposal was executed while the contribution reward was not register to the dao (it was mistakenly removed by schemeregisterar and then register back).
the subgraph is calling a "redeem" on execute event - which will revert if the scheme is not connected to the dao on this moment .
