### ISSUE TITLE
order proposals by confidence

### ISSUE THREAD

**Issue by dkent600** [daostack/subgraph#256]
We need to be able to sort queued proposals by confidence (or "score" as it is called in the GP contract).  If we are to implement paging when sorting, it is my understanding that this needs to be computed in subgraph.

**Comment by orenyodfat** [comment]
it was agreed that the confidence will not be calculated by the subgraph .

**Comment by A-Zak** [comment]
@orenyodfat, it is now needed for this to be calculated on the subgraph.
Two reasons:
1. Because the subgraph has a 100 item limit per query, we can't do this calculation on the client.
2. We could theoretically load all the pages and then sort on the client side, but that is a wrong way of doing it.

@jellegerbrandy anything you think is worth adding?
