### ISSUE TITLE
Proposal stage not updated

### ISSUE THREAD

**Issue by A-Zak** [daostack/subgraph#329]
This proposal was executed by pat:
`Proposal` - https://alchemy.daostack.io/dao/0x294f999356ed03347c7a23bcbcf8d33fa41dc830/proposal/0xea072e9afbfaaf8464f4d6d19a8d3ae7ee6f1bd6b141f4652e4da55d186d0d69
`Pat's transaction` - https://etherscan.io/tx/0x85c339cfd5e14cedaafb5961d436fc3c7c15b8dceff875ab45f2ff4733bc3aae

I can see that the money was indeed transferred, but the subgraph still shows the proposal as boosted:
https://subgraph.daostack.io/subgraphs/name/v24/graphql?query=%7B%0A%20%20proposals%20(where%3A%20%7Bid%3A%20%220xea072e9afbfaaf8464f4d6d19a8d3ae7ee6f1bd6b141f4652e4da55d186d0d69%22%7D)%20%7B%0A%20%20%20%20title%0A%20%20%20%20stage%0A%20%20%7D%0A%7D%0A%20%20%20%20

Related to alchemy issue - https://github.com/daostack/alchemy/issues/1123

**Comment by orenyodfat** [comment]
- PravduhDAO voting params looks unusual 
proposerRepReward  has a very big value 
      -50000000000000000000000000000000000000
It might be that the intent of that was to give a much small number (in ether units) and there was no attention to the fact that our migration script multiply this value by wei(10*18) as it expect to get that in wei unit.
The subgraph crash was due an attempt to calc the redeem reward for the proposer 
The total rep in the dao reached to 300000000000000042539092246287720199611 after few proposals ..
Trying to redeem the proposer rep cannot be done any more and cause the tx to revert in the reputation contract (due to safe math).
