### ISSUE TITLE
sometimes tests failing on travis.

### ISSUE THREAD

**Issue by orenyodfat** [daostack/subgraph#74]

**Comment by jellegerbrandy** [comment]
would be useful to provide some links to failing builds :-)

**Comment by ben-kaufman** [comment]
https://travis-ci.org/daostack/subgraph/builds/484980166

**Comment by ben-kaufman** [comment]
This will pass when restarting the build, other Travis instance passed.

**Comment by ben-kaufman** [comment]
It seems that (at least in this one) the issue was that the subgraph didn't update after the second stake on the proposal in the domain test was placed. I'm not sure what causes it as it happens only in Travis and only in small part of the runs. Maybe for some reason, the subgraph takes too long to update or completely misses the update, but it's really hard to tell.

**Comment by ben-kaufman** [comment]
After checking further it indeed seems that the test in Travis fails sometimes because on Travis the graph-node is updated slower than the test runs. An easy fix is to add some sleep between actions in the test to make sure it updates on time. Any other suggestions?

**Comment by jellegerbrandy** [comment]
Yes!
please please please  try to not use sleep time :-) It will just make everything worse (and slow :-))

So in this case, it seems the problem is that you test for an update on graphql but are not sure if the system has had the time to execute the update. So you could use this helper functionthat I use in the client lib for those kind of situations: https://github.com/daostack/client/blob/master/test/utils.ts#L94

And if you have a function like `function statkesAreUpdated() { return querythesubgraphforstakes().length >= 2 }`, you can then write `await waitUntilTrue(stakesAreUpdated)`.
